# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements


def load_arguments(self, _):  # pylint: disable=unused-argument
    with self.argument_context('cleanroom frontend collaboration contract list') as c:
        c.argument('collaboration_name', type=str, required=True, help='The name of the collaboration.')
    
    with self.argument_context('cleanroom frontend collaboration contract show') as c:
        c.argument('collaboration_name', type=str, required=True, help='The name of the collaboration.')
        c.argument('contract_name', type=str, required=True, help='The name of the contract.')