# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements

from knack.log import get_logger


logger = get_logger(__name__)

def collaboration_contract_list(collaboration_name: str):
    """List contracts in a collaboration."""
    print(f"Listing contracts for collaboration: {collaboration_name}")

def collaboration_contract_show(collaboration_name: str, contract_name: str):
    """Show details of a specific contract in a collaboration."""
    print(f"Showing contract '{contract_name}' for collaboration: {collaboration_name}")